# This workflow installs the package on Python 3.8, runs the tests and builds the docs
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# The main purpose for this weekly test is to check against WB API changes.

name: weekly

on:
  schedule:
    # see https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
    # 05:00 UTC = 06:00 CET = 07:00 CEST
    - cron: "0 5 * * TUE"

jobs:
  pytest:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.8'

      fail-fast: false


    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} py${{ matrix.python-version }}
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Pandoc
      uses: r-lib/actions/setup-pandoc@v1

    - name: Install dependencies and package
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Test with pytest
      run: |
        pytest tests --remote --slow
    - name: Build the docs
      run: |
        cd doc
        make html
        cd ..